name: atomicoat
description: A coating thickness measurement and analysis app.

publish_to: 'none'

version: 2.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.4.0
  intl: ^0.19.0
  uuid: ^4.5.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  fl_chart: ^0.70.0
  google_fonts: ^6.2.1
  bcrypt: ^1.1.3
  table_calendar: ^3.0.8
  flutter_svg: ^2.0.7
  sqflite: ^2.2.8+1
  path: ^1.8.3
  pdf: ^3.10.3
  path_provider: ^2.0.15
  open_file: ^3.2.1
  icon_badge: ^1.0.0
  animated_bottom_navigation_bar: ^1.3.3
  percent_indicator: ^4.2.2
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.1.0
  animated_theme_switcher: ^2.0.8
  glassmorphism: ^3.0.0
  animations: ^2.0.3
  flutter_animate: ^4.1.1+1
  audioplayers: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  crypto: any
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  mockito: ^5.4.4
  test: ^1.24.9
  logger: ^2.0.2+1
  supabase_flutter: ^2.3.4
  equatable: any
  flutter_launcher_icons: ^0.14.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: any

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/ald_system_diagram.png
    - assets/initial_components.json
    - assets/atomicoat_app_icon.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/atomicoat_app_icon.png"